# Generated by Django 3.0.7 on 2020-07-26 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaccount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='profile_image',
        ),
    ]
