# Generated by Django 3.0.7 on 2020-07-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaccount', '0002_auto_20200708_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.IntegerField(),
        ),
    ]
